### PR TITLE
Add Half-normal node

### PR DESCRIPTION
**Pull request by albertpod**

### CODE REVIEW

**Comment by albertpod** [comment]
ping @bvdmitri

**Comment by albertpod** [comment]
@bvdmitri note that there are no tests for prod of HalfNormal and Gamma, besides, I can't figure out why `check_type_promotion = true` fails.

I've also fixed the namings in `InverseGamma` tests.

**Comment by bvdmitri** [comment]
The fail in `check_type_promotion` is probably due to the `Inf` which is of type `Float64`

**Comment by albertpod** [comment]
ping @bvdmitri

**Review by bvdmitri — APPROVED** [review]

**Pull request merged**
