### PR TITLE
Clean demo notebooks and docs

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by bvdmitri** [comment]
Thanks @pitmonticone! I'll review this PR as soon as I can.

**Review by bvdmitri — APPROVED** [review]
That is an amazing PR and a lot of work! All changes look reasonable to me. Big thanks @pitmonticone .

**Comment by bvdmitri** [comment]
@pitmonticone IMO PR is ready to merge, but just in case I'll wait for your confirmation.

**Comment by pitmonticone** [comment]
Thank you @bvdmitri for your kind words. I confirm.

**Pull request merged**
